Gantt adventures visualization exercise
blacklabel/highcharts-fundamentals pull request #10
Opened 2023-09-06 10:53 UTC by KamilKubik

2023-09-13 21:59 UTC, Vazonik requested changes
Nice! Only small changes to the markdown indentations would be good (you can automatically commit my suggestions).

I'm wondering if there is any way to better present the all data in the illustration so that I don't have to wait for the gif to expand. Maybe an image with an expanded Gantt with all visible points?

2023-09-13 21:59 UTC, Vazonik commented on highcharts-api/highcharts-gantt/2-adventures-visualization/README.md
> +- There should be a gray shadow showing a place, where the element will be dropped (as shown in a gif).
Missing indents
```suggestion
    - A drag should be available only in a range of the x-axis.
    - The dropped element should always position itself in the range of a particular day (as shown in a gif).
    - There should be a gray shadow showing a place, where the element will be dropped (as shown in a gif).
```

2023-09-13 21:59 UTC, Vazonik commented on highcharts-api/highcharts-gantt/2-adventures-visualization/README.md
> +- After the drillup, the navigator should be backed to the previous state, showing the whole series.
```suggestion
    - After the drilldown, the navigator should show the displayed points (as shown in a gif).
    - After the drillup, the navigator should be backed to the previous state, showing the whole series.
```

2023-09-18 07:09 UTC, pawellysy approved these changes
LGTM

2023-09-18 13:33 UTC, mfilipiec approved these changes
I can't notice anything more than David, so LGTM 😅

2023-09-19 06:51 UTC, Vazonik approved these changes
LGTM, thanks!

2023-09-19 10:03 UTC, mfilipiec approved these changes

2023-09-19 10:03 UTC, merged