Added highcharts/3-minimal-charts
blacklabel/highcharts-fundamentals pull request #12
Opened 2023-09-15 13:20 UTC by mfilipiec

2023-09-15 14:11 UTC, Vazonik requested changes
Nice! Just a small suggestion regarding the content of the readme and a typo fix.

2023-09-15 14:11 UTC, Vazonik commented on highcharts-api/highcharts/3-minimal-charts/README.md
> +Create 4 minmal charts that show only series without other chart elements as in the gif below. Use CSS styles in such a way that the charts take up the available space in the parent element. Some cha
Why should formatting be different only for the pie chart? It seems to me that in the gif it is different for each of the charts.
```suggestion
Create 4 minimal charts that show only series without other chart elements, as in the gif below. Use CSS styles in such a way that the charts take up the available space in the parent element. Some chart options are common and some are individual, so use the method learned in the previous task. Also, take into account the formatting and behavior of the tooltip. Everything should be displayed in small charts and the formatting should be different for the pie chart.
```

2023-09-15 14:47 UTC, Vazonik approved these changes

2023-09-16 14:25 UTC, pawellysy approved these changes
LGTM

2023-09-19 09:16 UTC, merged