Stock/7 custom popup
blacklabel/highcharts-fundamentals pull request #24
Opened 2023-09-19 07:57 UTC by pawellysy

2023-09-19 09:26 UTC, Vazonik requested changes
Nice task, requested some small fixes.

2023-09-19 09:26 UTC, Vazonik commented on highcharts-api/highcharts-stock/7-custom-popup/README.md
> +The modal window should show in the middle of the chart, with a simple form. There should be one input field, which allows the user to change the color of the annotation, and the submit button. When
```suggestion
Create a custom popup for the annotation module. When selecting annotation (clicking on it) the custom popup should show.
The modal window should show in the middle of the chart, with a simple form. There should be one input field, which allows the user to change the color of the annotation, and the submit button. When the submit button is clicked, the custom popup should disappear, and the options should be applied to the annotation. There should also be a close button to hide the popup with no effect. For reference, see the gif below.
```

2023-09-19 09:26 UTC, Vazonik commented on highcharts-api/highcharts-stock/7-custom-popup/main.js
> +});
Something wrong happened with the indentations. Would be good to tidy it up.

2023-09-19 10:02 UTC, mfilipiec approved these changes
LGTM

2023-09-20 07:54 UTC, Vazonik approved these changes
Thanks!

2023-09-20 10:36 UTC, merged