stock/2-custom-stocktools-buttons
blacklabel/highcharts-fundamentals pull request #25
Opened 2023-09-19 09:10 UTC by pawellysy

2023-09-19 09:17 UTC, Vazonik requested changes
Thanks, just two typo-fix suggestions in readme.

2023-09-19 09:17 UTC, Vazonik commented on highcharts-api/highcharts-stock/2-custom-stocktools-buttons/README.md
> +Create a custom Stock tools button, which will be responsible for toggeling the live data update.
```suggestion
Create a custom Stock tools button, which will be responsible for toggling the live data update.
```

2023-09-19 09:17 UTC, Vazonik commented on highcharts-api/highcharts-stock/2-custom-stocktools-buttons/README.md
> +Add any icon to that button (customly created, or fetched from the internet, or added to local project).
```suggestion
Add any icon to that button (custom-created, fetched from the internet, or added to the local project).
```

2023-09-20 07:51 UTC, Vazonik approved these changes

2023-09-20 10:41 UTC, mfilipiec approved these changes

2023-09-20 10:41 UTC, merged